<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
    <PackageReference Include="Volo.Abp.Autofac" />
    <ProjectReference Include="../UltimateHospital.RuntimeInfrastructure/UltimateHospital.RuntimeInfrastructure.csproj" />
    <ProjectReference Include="../../../src/UltimateHospital.ServiceDefaults/UltimateHospital.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
